# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_gui(object):
    def setupUi(self, gui):
        gui.setObjectName("gui")
        gui.resize(380, 500)
        self.centralwidget = QtWidgets.QWidget(parent=gui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 370, 311, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 341, 241))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 121, 16))
        self.label_3.setObjectName("label_3")
        self.lbCam = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbCam.setGeometry(QtCore.QRect(30, 50, 331, 251))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lbCam.setFont(font)
        self.lbCam.setMouseTracking(False)
        self.lbCam.setTabletTracking(False)
        self.lbCam.setAcceptDrops(False)
        self.lbCam.setText("")
        self.lbCam.setScaledContents(False)
        self.lbCam.setWordWrap(False)
        self.lbCam.setOpenExternalLinks(False)
        self.lbCam.setObjectName("lbCam")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(29, 50, 321, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.camera = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.camera.setContentsMargins(0, 0, 0, 0)
        self.camera.setObjectName("camera")
        self.BtStart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BtStart.setGeometry(QtCore.QRect(30, 320, 75, 23))
        self.BtStart.setObjectName("BtStart")
        self.BtLogout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BtLogout.setGeometry(QtCore.QRect(250, 10, 75, 23))
        self.BtLogout.setObjectName("BtLogout")
        self.BtStop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BtStop.setGeometry(QtCore.QRect(280, 320, 75, 23))
        self.BtStop.setObjectName("BtStop")
        gui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=gui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 21))
        self.menubar.setObjectName("menubar")
        gui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=gui)
        self.statusbar.setObjectName("statusbar")
        gui.setStatusBar(self.statusbar)

        self.retranslateUi(gui)
        QtCore.QMetaObject.connectSlotsByName(gui)

    def retranslateUi(self, gui):
        _translate = QtCore.QCoreApplication.translate
        gui.setWindowTitle(_translate("gui", "MainWindow"))
        self.label.setText(_translate("gui", "Waring:"))
        self.label_3.setText(_translate("gui", "User: "))
        self.BtStart.setText(_translate("gui", "Start"))
        self.BtLogout.setText(_translate("gui", "Logout"))
        self.BtStop.setText(_translate("gui", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gui = QtWidgets.QMainWindow()
    ui = Ui_gui()
    ui.setupUi(gui)
    gui.show()
    sys.exit(app.exec())
