# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(380, 500)
        Login.setStyleSheet("background-color:rgb(219, 255, 249)")
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 70, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 160, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 40, 12)")
        self.label_3.setObjectName("label_3")
        self.BTlogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BTlogin.setGeometry(QtCore.QRect(140, 280, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BTlogin.setFont(font)
        self.BTlogin.setStyleSheet("background-color: rgb(7, 255, 36);")
        self.BTlogin.setObjectName("BTlogin")
        self.user = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user.setGeometry(QtCore.QRect(80, 100, 231, 41))
        font = QtGui.QFont()
        font.setItalic(True)
        self.user.setFont(font)
        self.user.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.user.setText("")
        self.user.setObjectName("user")
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setGeometry(QtCore.QRect(80, 190, 231, 41))
        font = QtGui.QFont()
        font.setItalic(True)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 21))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label.setText(_translate("Login", "User "))
        self.label_2.setText(_translate("Login", "Password"))
        self.label_3.setText(_translate("Login", "LOGIN"))
        self.BTlogin.setText(_translate("Login", "Login"))
        self.user.setPlaceholderText(_translate("Login", "Enter user name"))
        self.password.setPlaceholderText(_translate("Login", "Enter password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
