//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViPham
    {
        public int idViPham { get; set; }
        public int idUser { get; set; }
        public Nullable<System.DateTime> ngayGio { get; set; }
        public int idLoiViPham { get; set; }
    
        public virtual LoiViPham LoiViPham { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
